// ═══════════════════════════════════════════════════════════════
// استوديو تصميم تطبيق العميل (CMS) — الأقسام 1 إلى 28
// كل شيء اختياري وقابل للإظهار/الإخفاء (Toggle)
// ═══════════════════════════════════════════════════════════════
import { SubscriberCMS } from '@/types/cms';
import { CMS_TEMPLATES } from '@/data/cms-defaults';
import { uid } from '@/lib/random';
import { useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Building2, User, Monitor, Smartphone, Menu, Type, Layout, Palette, LayoutTemplate, Plus, X, Upload, Eye, EyeOff, Star, Image, Home, Wallet, TrendingUp, CreditCard, ArrowLeftRight, Settings, Shield, HelpCircle, LogOut, Search, Bell, Moon, Globe, Award, Crown, Heart, BarChart3, Timer, FileText, MapPin, MessageSquare, Calendar, AlertTriangle, FileDown, Target, Clock, Receipt, Sparkles } from 'lucide-react';

const ICONS: Record<string, React.ComponentType<any>> = { home:Home, wallet:Wallet, profits:TrendingUp, operations:CreditCard, withdraw:ArrowLeftRight, account:User, settings:Settings, shield:Shield, search:Search, bell:Bell, moon:Moon, globe:Globe, star:Star, award:Award, crown:Crown, heart:Heart, help:HelpCircle, logout:LogOut, file:FileText, chart:BarChart3, timer:Timer, target:Target, clock:Clock };
function Ic({ name, size=15 }: { name:string; size?:number }) { const C = ICONS[name] || Star; return <C size={size} />; }
function Toggle({ label, checked, onChange }: { label:string; checked:boolean; onChange:(v:boolean)=>void }) { return <div className="flex items-center justify-between py-1.5"><label className="text-xs font-bold text-slate-700">{label}</label><Switch checked={checked} onCheckedChange={onChange} /></div>; }
function Clr({ label, value, onChange }: { label:string; value:string; onChange:(v:string)=>void }) { return <div className="flex items-center gap-2"><label className="text-[10px] font-bold text-slate-600 min-w-[70px]">{label}</label><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-7 w-8 rounded border border-slate-200 cursor-pointer" /><Input value={value} onChange={e=>onChange(e.target.value)} className="h-7 text-[10px] font-mono flex-1" /></div>; }
function IconBtn({ value, onChange }: { value:string; onChange:(v:string)=>void }) { const [open, setOpen] = useState(false); return <div className="relative"><button type="button" onClick={()=>setOpen(!open)} className="h-8 w-8 rounded-lg border border-slate-200 bg-white flex items-center justify-center hover:bg-slate-50"><Ic name={value} /></button>{open && <div className="absolute z-50 top-9 right-0 bg-white border border-slate-200 rounded-xl shadow-xl p-2 grid grid-cols-6 gap-1 w-56">{Object.keys(ICONS).map(k=><button key={k} type="button" onClick={()=>{onChange(k);setOpen(false);}} className={`p-1.5 rounded-lg flex items-center justify-center ${value===k?'bg-blue-100 text-blue-700':'hover:bg-slate-100 text-slate-600'}`}><Ic name={k} size={14} /></button>)}</div>}</div>; }
function SH({ icon, title, num }: { icon:React.ReactNode; title:string; num:string }) { return <div className="flex items-center justify-between mb-2"><h4 className="text-sm font-black text-slate-800 flex items-center gap-2">{icon}{title}</h4><Badge variant="outline" className="text-[10px]">{num}</Badge></div>; }

type T = 'company'|'profile'|'topbar'|'bottombar'|'sidebar'|'colors'|'texts'|'sections'|'cards'|'charts'|'counters'|'achievements'|'banners'|'datatable'|'map'|'messages'|'calendar'|'gallery'|'alerts'|'docs'|'progress'|'countdown'|'invoice'|'templates'|'design'|'widgets';

export function CMSBuilder({ cms, onChange }: { cms: SubscriberCMS; onChange: (c: SubscriberCMS) => void }) {
  const [tab, setTab] = useState<T>('company');
  const up = <K extends keyof SubscriberCMS>(k: K, p: Partial<SubscriberCMS[K]>) => onChange({ ...cms, [k]: { ...(cms[k] as any), ...p } });
  const applyTpl = (id: string) => { const t = CMS_TEMPLATES.find(x => x.id === id); if (!t) return; const n = { ...cms }; if (t.design) n.design = { ...n.design, ...t.design, colors: { ...n.design.colors, ...(t.design.colors || {}) } }; if (t.topBar) n.topBar = { ...n.topBar, ...t.topBar }; if (t.bottomBar) n.bottomBar = { ...n.bottomBar, ...t.bottomBar }; if (t.sideBar) n.sideBar = { ...n.sideBar, ...t.sideBar }; n.templateId = id; onChange(n); toast.success(`تم تطبيق "${t.name}"`); };
  const mkText = () => ({ id:uid(), title:'', content:'', icon:'star', color:'#3b82f6', size:'medium' as const, align:'right' as const, bgType:'none' as const, bgValue:'', border:'none' as const, type:'normal' as const, location:'summary' as const, visible:true, expiryDate:'' });
  const mkSec = () => ({ id:uid(), title:'', subtitle:'', icon:'star', description:'', images:[], imageDisplay:'single' as const, imageSize:'medium' as const, videoUrl:'', buttons:[], location:'home' as const, order:cms.sections.length, collapsible:false, defaultState:'open' as const, bgColor:'#ffffff', style:'card' as const, visible:true, dateFrom:'', dateTo:'' });
  const mkCard = () => ({ id:uid(), title:'', value:'', icon:'wallet', color:'#3b82f6', change:'', sparkline:[], size:'medium' as const, visible:true, order:cms.infoCards.length });
  const mkChart = () => ({ id:uid(), type:'line' as const, title:'', dataType:'profits' as const, period:'30d' as const, colors:['#3b82f6'], showNumbers:true, size:'medium' as const, visible:true, order:cms.charts.length });
  const mkCounter = () => ({ id:uid(), value:0, prefix:'', suffix:'', title:'', icon:'star', color:'#3b82f6', duration:2 as const, visible:true, order:cms.counters.length });
  const mkAch = () => ({ id:uid(), name:'', icon:'⭐', color:'gold' as const, customColor:'', description:'', dateEarned:'', visible:true, order:cms.achievements.length });
  const mkBanner = () => ({ id:uid(), text:'', image:'', url:'', color:'#3b82f6', location:'top' as const, closable:true, expiryDate:'', visible:true, order:cms.banners.length });
  const mkAlert = () => ({ id:uid(), text:'', type:'info' as const, icon:'bell', closable:true, location:'top' as const, visible:true, order:cms.alerts.length });
  const mkDoc = () => ({ id:uid(), name:'', fileData:'', fileType:'', icon:'file', size:'', date:'', showDownload:true, visible:true, order:cms.documents.length });
  const mkProg = () => ({ id:uid(), title:'', current:0, target:100, color:'#3b82f6', shape:'linear' as const, visible:true, order:cms.progressBars.length });
  const mkCd = () => ({ id:uid(), title:'', targetDate:'', targetTime:'', color:'#3b82f6', size:'small' as const, visible:true, order:cms.countdowns.length });
  const updA = <T extends {id:string}>(k:keyof SubscriberCMS, i:number, p:Partial<T>) => { const a=[...(cms[k] as any[])]; a[i]={...a[i],...p}; onChange({...cms,[k]:a}); };
  const rmA = (k:keyof SubscriberCMS, id:string) => onChange({...cms,[k]:(cms[k] as any[]).filter(x=>x.id!==id)});

  const tabs: {id:T;label:string;icon:React.ReactNode}[] = [
    {id:'company',label:'الشركة',icon:<Building2 size={13}/>},{id:'profile',label:'الملف',icon:<User size={13}/>},{id:'topbar',label:'علوي',icon:<Monitor size={13}/>},{id:'bottombar',label:'سفلي',icon:<Smartphone size={13}/>},{id:'sidebar',label:'جانبي',icon:<Menu size={13}/>},{id:'colors',label:'ألوان',icon:<Palette size={13}/>},{id:'texts',label:'نصوص',icon:<Type size={13}/>},{id:'sections',label:'أقسام',icon:<Layout size={13}/>},{id:'cards',label:'بطاقات',icon:<CreditCard size={13}/>},{id:'charts',label:'رسوم',icon:<BarChart3 size={13}/>},{id:'counters',label:'عدادات',icon:<Timer size={13}/>},{id:'achievements',label:'أوسمة',icon:<Award size={13}/>},{id:'banners',label:'بانرات',icon:<Sparkles size={13}/>},{id:'datatable',label:'جدول',icon:<FileText size={13}/>},{id:'map',label:'خريطة',icon:<MapPin size={13}/>},{id:'messages',label:'رسائل',icon:<MessageSquare size={13}/>},{id:'calendar',label:'تقويم',icon:<Calendar size={13}/>},{id:'gallery',label:'معرض',icon:<Image size={13}/>},{id:'alerts',label:'تنبيهات',icon:<AlertTriangle size={13}/>},{id:'docs',label:'مستندات',icon:<FileDown size={13}/>},{id:'progress',label:'تقدم',icon:<Target size={13}/>},{id:'countdown',label:'عد تنازلي',icon:<Clock size={13}/>},{id:'invoice',label:'فاتورة',icon:<Receipt size={13}/>},{id:'templates',label:'قوالب',icon:<LayoutTemplate size={13}/>},{id:'design',label:'تصميم',icon:<Palette size={13}/>},{id:'widgets',label:'إضافات',icon:<Globe size={13}/>},
  ];

  return (
    <Card className="border-none shadow-sm ring-1 ring-slate-200 overflow-hidden">
      <div className="h-1.5 bg-gradient-to-r from-violet-500 via-indigo-500 to-blue-500" />
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between gap-3">
          <div><CardTitle className="text-sm font-black text-slate-800 flex items-center gap-2"><LayoutTemplate size={16} className="text-violet-600" /> استوديو تصميم تطبيق العميل — 28 قسم</CardTitle><CardDescription className="text-[11px] mt-0.5">كل مشترك = تطبيق مستقل. كل شيء اختياري (Toggle).</CardDescription></div>
          <Badge className="bg-violet-50 text-violet-700 border-violet-200 text-[10px]">CMS</Badge>
        </div>
      </CardHeader>
      <CardContent className="p-0">
        <Tabs value={tab} onValueChange={v=>setTab(v as T)}>
          <div className="border-b border-slate-100 px-3 overflow-x-auto"><TabsList className="bg-transparent h-auto py-1.5 gap-0.5 justify-start flex-nowrap">{tabs.map(t=><TabsTrigger key={t.id} value={t.id} className="flex items-center gap-1 px-2 py-1 text-[11px] font-bold rounded-lg data-[state=active]:bg-violet-100 data-[state=active]:text-violet-700 data-[state=inactive]:text-slate-500 whitespace-nowrap">{t.icon}{t.label}</TabsTrigger>)}</TabsList></div>
          <div className="p-4 space-y-3 max-h-[70vh] overflow-y-auto">

            {/* 1. الشركة */}
            <TabsContent value="company" className="mt-0 space-y-3">
              <SH icon={<Building2 size={14} className="text-violet-600"/>} title="🏢 هوية الشركة" num="1/28" />
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div><label className="text-[10px] font-bold text-slate-600">اسم الشركة</label><Input value={cms.company.name} onChange={e=>up('company',{name:e.target.value})} className="h-8 text-xs" /></div>
                <div><label className="text-[10px] font-bold text-slate-600">المختصر</label><Input value={cms.company.shortName} onChange={e=>up('company',{shortName:e.target.value})} className="h-8 text-xs" /></div>
                <div><label className="text-[10px] font-bold text-slate-600">الوصف</label><Input value={cms.company.description} onChange={e=>up('company',{description:e.target.value})} className="h-8 text-xs" /></div>
                <div><label className="text-[10px] font-bold text-slate-600">الموقع</label><Input value={cms.company.website} onChange={e=>up('company',{website:e.target.value})} className="h-8 text-xs" /></div>
                <div><label className="text-[10px] font-bold text-slate-600">البريد</label><Input value={cms.company.email} onChange={e=>up('company',{email:e.target.value})} className="h-8 text-xs" /></div>
                <div><label className="text-[10px] font-bold text-slate-600">الهاتف</label><div className="flex gap-1"><Input value={cms.company.phone} onChange={e=>up('company',{phone:e.target.value})} className="h-8 text-xs flex-1" /><Button variant="outline" size="sm" className={`h-8 px-2 text-[10px] ${cms.company.whatsappEnabled?'bg-green-50 text-green-700':''}`} onClick={()=>up('company',{whatsappEnabled:!cms.company.whatsappEnabled})}>WA</Button></div></div>
                <div><label className="text-[10px] font-bold text-slate-600">العنوان</label><Input value={cms.company.address} onChange={e=>up('company',{address:e.target.value})} className="h-8 text-xs" /></div>
                <div><label className="text-[10px] font-bold text-slate-600">السجل التجاري</label><Input value={cms.company.commercialReg} onChange={e=>up('company',{commercialReg:e.target.value})} className="h-8 text-xs" /></div>
              </div>
              <div className="flex flex-wrap gap-2 items-end">
                <div><label className="text-[10px] font-bold text-slate-600 block mb-1">الشعار</label><div className="flex items-center gap-1"><div className="w-9 h-9 rounded bg-slate-100 overflow-hidden flex items-center justify-center">{cms.company.logo?<img src={cms.company.logo} className="w-full h-full object-contain"/>:<Building2 size={14} className="text-slate-400"/>}</div><label className="h-8 px-2 rounded border border-slate-200 text-[10px] cursor-pointer flex items-center gap-1 hover:bg-slate-50"><Upload size={10}/>رفع<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>up('company',{logo:String(r.result||'')});r.readAsDataURL(f)}}}/></label></div></div>
                <div><label className="text-[10px] font-bold text-slate-600 block mb-1">Favicon</label><div className="flex items-center gap-1"><div className="w-7 h-7 rounded bg-slate-100 overflow-hidden flex items-center justify-center">{cms.company.favicon?<img src={cms.company.favicon} className="w-full h-full object-contain"/>:<span className="text-[8px] text-slate-400">fav</span>}</div><label className="h-7 px-2 rounded border border-slate-200 text-[10px] cursor-pointer flex items-center gap-1 hover:bg-slate-50"><Upload size={9}/><input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>up('company',{favicon:String(r.result||'')});r.readAsDataURL(f)}}}/></label></div></div>
                <div><label className="text-[10px] font-bold text-slate-600 block mb-1">صورة غلاف</label><label className="h-8 px-2 rounded border border-slate-200 text-[10px] cursor-pointer flex items-center gap-1 hover:bg-slate-50"><Upload size={10}/>رفع<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>up('company',{coverImage:String(r.result||'')});r.readAsDataURL(f)}}}/></label></div>
              </div>
              <div className="border-t border-slate-100 pt-2"><label className="text-[10px] font-bold text-slate-700 mb-1 block">السوشيال ميديا</label><div className="grid grid-cols-2 md:grid-cols-3 gap-2">{(['instagram','twitter','telegram','tiktok','linkedin','snapchat'] as const).map(s=><div key={s}><label className="text-[9px] text-slate-500">{s}</label><Input value={cms.company.social[s]} onChange={e=>up('company',{social:{...cms.company.social,[s]:e.target.value}})} className="h-7 text-[10px]" /></div>)}</div></div>
            </TabsContent>

            {/* 2. الملف الشخصي */}
            <TabsContent value="profile" className="mt-0 space-y-3">
              <SH icon={<User size={14} className="text-violet-600"/>} title="👤 الملف الشخصي للعميل" num="2/28" />
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div><label className="text-[10px] font-bold text-slate-600">صورة العميل</label><Select value={cms.clientProfile.avatarType} onValueChange={v=>up('clientProfile',{avatarType:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="upload">رفع</SelectItem><SelectItem value="auto">تلقائي</SelectItem><SelectItem value="hidden">إخفاء</SelectItem></SelectContent></Select></div>
                <div><label className="text-[10px] font-bold text-slate-600">شكل الصورة</label><Select value={cms.clientProfile.avatarShape} onValueChange={v=>up('clientProfile',{avatarShape:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="circle">دائرية</SelectItem><SelectItem value="square">مربعة</SelectItem><SelectItem value="rounded">مستديرة</SelectItem></SelectContent></Select></div>
                <div><label className="text-[10px] font-bold text-slate-600">اسم العرض</label><Select value={cms.clientProfile.displayMode} onValueChange={v=>up('clientProfile',{displayMode:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="original">الأصلي</SelectItem><SelectItem value="alias">مستعار</SelectItem><SelectItem value="hidden">إخفاء</SelectItem></SelectContent></Select></div>
                <div><label className="text-[10px] font-bold text-slate-600">اللقب</label><Input value={cms.clientProfile.title} onChange={e=>up('clientProfile',{title:e.target.value})} className="h-8 text-xs" /></div>
                <div><label className="text-[10px] font-bold text-slate-600">رقم العضوية</label><Input value={cms.clientProfile.memberNumber} onChange={e=>up('clientProfile',{memberNumber:e.target.value})} className="h-8 text-xs" /></div>
                <div><label className="text-[10px] font-bold text-slate-600">الشارة</label><Select value={cms.clientProfile.badge} onValueChange={v=>up('clientProfile',{badge:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">بدون</SelectItem><SelectItem value="vip">⭐ VIP</SelectItem><SelectItem value="premium">🏆 مميز</SelectItem><SelectItem value="platinum">💎 بلاتيني</SelectItem><SelectItem value="founder">🎖️ مؤسس</SelectItem></SelectContent></Select></div>
                <div><label className="text-[10px] font-bold text-slate-600">المستوى</label><Select value={cms.clientProfile.memberLevel} onValueChange={v=>up('clientProfile',{memberLevel:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">بدون</SelectItem><SelectItem value="bronze">Bronze</SelectItem><SelectItem value="silver">Silver</SelectItem><SelectItem value="gold">Gold</SelectItem><SelectItem value="platinum">Platinum</SelectItem><SelectItem value="diamond">Diamond</SelectItem></SelectContent></Select></div>
                <div><label className="text-[10px] font-bold text-slate-600">الحالة</label><Select value={cms.clientProfile.statusStyle} onValueChange={v=>up('clientProfile',{statusStyle:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">🟢 نشط</SelectItem><SelectItem value="pending">🟡 معلق</SelectItem><SelectItem value="stopped">🔴 موقوف</SelectItem><SelectItem value="new">🔵 جديد</SelectItem></SelectContent></Select></div>
                <div><label className="text-[10px] font-bold text-slate-600">الهاتف</label><Select value={cms.clientProfile.phoneDisplay} onValueChange={v=>up('clientProfile',{phoneDisplay:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="full">كامل</SelectItem><SelectItem value="partial">مخفي جزئياً</SelectItem><SelectItem value="hidden">مخفي</SelectItem></SelectContent></Select></div>
                <div><label className="text-[10px] font-bold text-slate-600">لون الاسم</label><div className="flex gap-1"><input type="color" value={cms.clientProfile.nameColor} onChange={e=>up('clientProfile',{nameColor:e.target.value})} className="h-8 w-8 rounded cursor-pointer" /><Input value={cms.clientProfile.nameColor} onChange={e=>up('clientProfile',{nameColor:e.target.value})} className="h-8 text-[10px] font-mono flex-1" /></div></div>
              </div>
              <div className="grid grid-cols-2 gap-2 border-t border-slate-100 pt-2"><Toggle label="إظهار البلد" checked={cms.clientProfile.showCountry} onChange={v=>up('clientProfile',{showCountry:v})} /><Toggle label="تاريخ الانضمام" checked={cms.clientProfile.showJoinDate} onChange={v=>up('clientProfile',{showJoinDate:v})} /></div>
              <div><label className="text-[10px] font-bold text-slate-600">نص تعريفي</label><Textarea value={cms.clientProfile.personalBio} onChange={e=>up('clientProfile',{personalBio:e.target.value})} rows={2} className="text-xs" /></div>
              <div className="border-t border-slate-100 pt-2"><label className="text-[10px] font-bold text-slate-600">خلفية البطاقة</label><div className="flex gap-2 items-center"><Select value={cms.clientProfile.cardBgType} onValueChange={v=>up('clientProfile',{cardBgType:v as any})}><SelectTrigger className="h-8 w-32 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="color">لون</SelectItem><SelectItem value="gradient">تدرج</SelectItem><SelectItem value="image">صورة</SelectItem><SelectItem value="transparent">شفافة</SelectItem></SelectContent></Select><Input value={cms.clientProfile.cardBackground} onChange={e=>up('clientProfile',{cardBackground:e.target.value})} className="h-8 text-[10px] flex-1 font-mono" /></div></div>
            </TabsContent>

            {/* 3. Top Bar */}
            <TabsContent value="topbar" className="mt-0 space-y-3">
              <SH icon={<Monitor size={14} className="text-violet-600"/>} title="📱 Top Bar" num="3/28" />
              <Toggle label="تفعيل" checked={cms.topBar.enabled} onChange={v=>up('topBar',{enabled:v})} />
              {cms.topBar.enabled && <div className="space-y-2 border-t border-slate-100 pt-3">
                <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                  <div><label className="text-[10px] font-bold text-slate-600">العنوان</label><Input value={cms.topBar.title} onChange={e=>up('topBar',{title:e.target.value})} className="h-8 text-xs" /></div>
                  <div><label className="text-[10px] font-bold text-slate-600">فرعي</label><Input value={cms.topBar.subtitle} onChange={e=>up('topBar',{subtitle:e.target.value})} className="h-8 text-xs" /></div>
                  <div><label className="text-[10px] font-bold text-slate-600">خلفية</label><div className="flex gap-1"><input type="color" value={cms.topBar.bgColor} onChange={e=>up('topBar',{bgColor:e.target.value})} className="h-8 w-8 rounded cursor-pointer" /><Input value={cms.topBar.bgColor} onChange={e=>up('topBar',{bgColor:e.target.value})} className="h-8 text-[10px] font-mono flex-1" /></div></div>
                  <div><label className="text-[10px] font-bold text-slate-600">لون النصوص</label><div className="flex gap-1"><input type="color" value={cms.topBar.textColor} onChange={e=>up('topBar',{textColor:e.target.value})} className="h-8 w-8 rounded cursor-pointer" /><Input value={cms.topBar.textColor} onChange={e=>up('topBar',{textColor:e.target.value})} className="h-8 text-[10px] font-mono flex-1" /></div></div>
                </div>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-1 border-t border-slate-100 pt-2">
                  <Toggle label="الشعار" checked={cms.topBar.showLogo} onChange={v=>up('topBar',{showLogo:v})} /><Toggle label="اسم العميل" checked={cms.topBar.showClientName} onChange={v=>up('topBar',{showClientName:v})} /><Toggle label="🔔 إشعارات" checked={cms.topBar.showNotifications} onChange={v=>up('topBar',{showNotifications:v})} /><Toggle label="🌙 داكن" checked={cms.topBar.showDarkMode} onChange={v=>up('topBar',{showDarkMode:v})} /><Toggle label="🔍 بحث" checked={cms.topBar.showSearch} onChange={v=>up('topBar',{showSearch:v})} /><Toggle label="🌐 لغة" checked={cms.topBar.showLanguage} onChange={v=>up('topBar',{showLanguage:v})} /><Toggle label="☰ قائمة" checked={cms.topBar.showMenu} onChange={v=>up('topBar',{showMenu:v})} /><Toggle label="ثابت" checked={cms.topBar.sticky} onChange={v=>up('topBar',{sticky:v})} />
                </div>
              </div>}
            </TabsContent>

            {/* 4-5. Bottom + Side Bar - simplified */}
            <TabsContent value="bottombar" className="mt-0 space-y-3">
              <SH icon={<Smartphone size={14} className="text-violet-600"/>} title="⬇️ Bottom Bar" num="4/28" />
              <Toggle label="تفعيل" checked={cms.bottomBar.enabled} onChange={v=>up('bottomBar',{enabled:v})} />
              {cms.bottomBar.enabled && <div className="space-y-2 border-t border-slate-100 pt-3">
                <div className="grid grid-cols-2 gap-2"><Select value={String(cms.bottomBar.buttonCount)} onValueChange={v=>up('bottomBar',{buttonCount:Number(v) as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="3">3</SelectItem><SelectItem value="4">4</SelectItem><SelectItem value="5">5</SelectItem></SelectContent></Select><Select value={cms.bottomBar.style} onValueChange={v=>up('bottomBar',{style:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="flat">مسطح</SelectItem><SelectItem value="raised">بارز</SelectItem><SelectItem value="rounded">دائري</SelectItem><SelectItem value="glass">زجاجي</SelectItem></SelectContent></Select></div>
                <div className="border-t border-slate-100 pt-2"><div className="flex items-center justify-between mb-1"><label className="text-[10px] font-bold text-slate-700">الأزرار ({cms.bottomBar.buttons.length})</label><Button variant="outline" size="sm" className="h-6 text-[10px]" onClick={()=>up('bottomBar',{buttons:[...cms.bottomBar.buttons,{id:uid(),icon:'star',label:'جديد',action:'home',highlighted:false,color:'#3b82f6',badge:0,visible:true,order:cms.bottomBar.buttons.length}]})}><Plus size={10}/></Button></div>{cms.bottomBar.buttons.map((b,i)=><div key={b.id} className="flex items-center gap-1 mb-1 p-1 rounded border border-slate-100 bg-slate-50/50"><IconBtn value={b.icon} onChange={v=>updA('bottomBar',i,{icon:v}as any)} /><Input value={b.label} onChange={e=>updA('bottomBar',i,{label:e.target.value}as any)} className="h-7 text-[10px] w-16" /><input type="color" value={b.color} onChange={e=>updA('bottomBar',i,{color:e.target.value}as any)} className="h-7 w-6 rounded cursor-pointer" /><Button variant="ghost" size="sm" className={`h-6 text-[10px] ${b.highlighted?'bg-amber-100 text-amber-700':'text-slate-400'}`} onClick={()=>updA('bottomBar',i,{highlighted:!b.highlighted}as any)}>★</Button><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>up('bottomBar',{buttons:cms.bottomBar.buttons.filter(x=>x.id!==b.id)})}><X size={10}/></Button></div>)}</div>
              </div>}
            </TabsContent>

            <TabsContent value="sidebar" className="mt-0 space-y-3">
              <SH icon={<Menu size={14} className="text-violet-600"/>} title="📌 Side Bar" num="5/28" />
              <Toggle label="تفعيل" checked={cms.sideBar.enabled} onChange={v=>up('sideBar',{enabled:v})} />
              {cms.sideBar.enabled && <div className="space-y-2 border-t border-slate-100 pt-3">
                <div className="grid grid-cols-2 gap-2"><Select value={cms.sideBar.position} onValueChange={v=>up('sideBar',{position:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="right">يمين</SelectItem><SelectItem value="left">يسار</SelectItem></SelectContent></Select><Select value={cms.sideBar.behavior} onValueChange={v=>up('sideBar',{behavior:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="fixed">ثابت</SelectItem><SelectItem value="collapsible">قابل للطي</SelectItem><SelectItem value="press-only">بالضغط</SelectItem></SelectContent></Select></div>
                <div className="grid grid-cols-2 gap-1 border-t border-slate-100 pt-2"><Toggle label="صورة" checked={cms.sideBar.header.showAvatar} onChange={v=>up('sideBar',{header:{...cms.sideBar.header,showAvatar:v}})} /><Toggle label="اسم" checked={cms.sideBar.header.showName} onChange={v=>up('sideBar',{header:{...cms.sideBar.header,showName:v}})} /><Toggle label="حالة" checked={cms.sideBar.header.showStatus} onChange={v=>up('sideBar',{header:{...cms.sideBar.header,showStatus:v}})} /><Toggle label="إعدادات" checked={cms.sideBar.header.showSettings} onChange={v=>up('sideBar',{header:{...cms.sideBar.header,showSettings:v}})} /></div>
                <div className="border-t border-slate-100 pt-2"><div className="flex items-center justify-between mb-1"><label className="text-[10px] font-bold text-slate-700">العناصر ({cms.sideBar.items.length})</label><Button variant="outline" size="sm" className="h-6 text-[10px]" onClick={()=>up('sideBar',{items:[...cms.sideBar.items,{id:uid(),icon:'star',label:'عنصر',description:'',action:'home',badge:0,color:'',group:'',visible:true,order:cms.sideBar.items.length,separator:false}]})}><Plus size={10}/></Button></div>{cms.sideBar.items.map((it,i)=><div key={it.id} className="flex items-center gap-1 mb-1 p-1 rounded border border-slate-100 bg-slate-50/50"><IconBtn value={it.icon} onChange={v=>updA('sideBar',i,{icon:v}as any)} /><Input value={it.label} onChange={e=>updA('sideBar',i,{label:e.target.value}as any)} className="h-7 text-[10px] w-16" /><Input value={it.group} onChange={e=>updA('sideBar',i,{group:e.target.value}as any)} className="h-7 text-[10px] w-12" placeholder="مجموعة" /><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>up('sideBar',{items:cms.sideBar.items.filter(x=>x.id!==it.id)})}><X size={10}/></Button></div>)}</div>
              </div>}
            </TabsContent>

            {/* 6. الألوان */}
            <TabsContent value="colors" className="mt-0 space-y-3">
              <SH icon={<Palette size={14} className="text-violet-600"/>} title="🎨 الألوان والثيمات" num="6/28" />
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">{(['primary','secondary','success','warning','danger','bgMain','bgCards','textMain','textSecondary','borders'] as const).map(k=>{const l:Record<string,string>={primary:'الرئيسي',secondary:'الثانوي',success:'نجاح',warning:'تحذير',danger:'خطر',bgMain:'خلفية',bgCards:'بطاقات',textMain:'نصوص',textSecondary:'فرعي',borders:'حدود'};return <Clr key={k} label={l[k]} value={cms.design.colors[k]} onChange={v=>up('design',{colors:{...cms.design.colors,[k]:v}})}/>})}</div>
              <Toggle label="تفعيل الوضع الداكن" checked={cms.design.darkMode.enabled} onChange={v=>up('design',{darkMode:{...cms.design.darkMode,enabled:v}})} /><Toggle label="تبديل تلقائي" checked={cms.design.darkMode.autoSwitch} onChange={v=>up('design',{darkMode:{...cms.design.darkMode,autoSwitch:v}})} />
            </TabsContent>

            {/* 7. النصوص */}
            <TabsContent value="texts" className="mt-0 space-y-3">
              <SH icon={<Type size={14} className="text-violet-600"/>} title="✏️ النصوص المخصصة" num="7/28" />
              <Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('texts',{texts:[...cms.texts,mkText()]})}><Plus size={10}/> إضافة</Button>
              {cms.texts.map((t,i)=><div key={t.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={t.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{t.visible?'ظاهر':'مخفي'}</Badge><div className="flex gap-1"><Button variant="ghost" size="sm" className="h-6" onClick={()=>updA('texts',i,{visible:!t.visible})}>{t.visible?<EyeOff size={10}/>:<Eye size={10}/>}</Button><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('texts',t.id)}><X size={10}/></Button></div></div><div className="grid grid-cols-2 gap-2"><Input value={t.title} onChange={e=>updA('texts',i,{title:e.target.value})} placeholder="عنوان" className="h-7 text-[10px]" /><Select value={t.type} onValueChange={v=>updA('texts',i,{type:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['normal','alert','success','danger','info'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><Textarea value={t.content} onChange={e=>updA('texts',i,{content:e.target.value})} rows={2} placeholder="{الاسم} {الأرباح} {الرصيد}" className="text-[10px]" /></div>)}
              {cms.texts.length===0&&<p className="text-center text-xs text-slate-400 py-4">لا توجد نصوص</p>}
            </TabsContent>

            {/* 8. الأقسام */}
            <TabsContent value="sections" className="mt-0 space-y-3">
              <SH icon={<Layout size={14} className="text-violet-600"/>} title="📂 الأقسام المخصصة" num="8/28" />
              <Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('sections',{sections:[...cms.sections,mkSec()]})}><Plus size={10}/> إضافة</Button>
              {cms.sections.map((s,i)=><div key={s.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={s.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{s.visible?'ظاهر':'مخفي'}</Badge><div className="flex gap-1"><Button variant="ghost" size="sm" className="h-6" onClick={()=>updA('sections',i,{visible:!s.visible})}>{s.visible?<EyeOff size={10}/>:<Eye size={10}/>}</Button><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('sections',s.id)}><X size={10}/></Button></div></div><div className="grid grid-cols-2 gap-2"><Input value={s.title} onChange={e=>updA('sections',i,{title:e.target.value})} placeholder="عنوان" className="h-7 text-[10px]" /><Input value={s.subtitle} onChange={e=>updA('sections',i,{subtitle:e.target.value})} placeholder="فرعي" className="h-7 text-[10px]" /></div><Textarea value={s.description} onChange={e=>updA('sections',i,{description:e.target.value})} rows={2} className="text-[10px]" /></div>)}
              {cms.sections.length===0&&<p className="text-center text-xs text-slate-400 py-4">لا توجد أقسام</p>}
            </TabsContent>

            {/* 9. بطاقات */}
            <TabsContent value="cards" className="mt-0 space-y-3">
              <SH icon={<CreditCard size={14} className="text-violet-600"/>} title="🃏 بطاقات المعلومات" num="9/28" />
              <Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('infoCards',{infoCards:[...cms.infoCards,mkCard()]})}><Plus size={10}/> إضافة بطاقة</Button>
              {cms.infoCards.map((c,i)=><div key={c.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={c.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{c.visible?'ظاهر':'مخفي'}</Badge><div className="flex gap-1"><Button variant="ghost" size="sm" className="h-6" onClick={()=>updA('infoCards',i,{visible:!c.visible})}>{c.visible?<EyeOff size={10}/>:<Eye size={10}/>}</Button><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('infoCards',c.id)}><X size={10}/></Button></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2"><Input value={c.title} onChange={e=>updA('infoCards',i,{title:e.target.value})} placeholder="العنوان" className="h-7 text-[10px]" /><Input value={c.value} onChange={e=>updA('infoCards',i,{value:e.target.value})} placeholder="القيمة" className="h-7 text-[10px]" /><IconBtn value={c.icon} onChange={v=>updA('infoCards',i,{icon:v}as any)} /><input type="color" value={c.color} onChange={e=>updA('infoCards',i,{color:e.target.value}as any)} className="h-7 w-8 rounded cursor-pointer" /></div><Input value={c.change} onChange={e=>updA('infoCards',i,{change:e.target.value})} placeholder="↗ +12%" className="h-7 text-[10px]" /></div>)}
            </TabsContent>

            {/* 10. الرسوم */}
            <TabsContent value="charts" className="mt-0 space-y-3">
              <SH icon={<BarChart3 size={14} className="text-violet-600"/>} title="📊 الرسوم البيانية" num="10/28" />
              <Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('charts',{charts:[...cms.charts,mkChart()]})}><Plus size={10}/> إضافة</Button>
              {cms.charts.map((ch,i)=><div key={ch.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={ch.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{ch.visible?'ظاهر':'مخفي'}</Badge><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('charts',ch.id)}><X size={10}/></Button></div><div className="grid grid-cols-2 gap-2"><Input value={ch.title} onChange={e=>updA('charts',i,{title:e.target.value})} placeholder="العنوان" className="h-7 text-[10px]" /><Select value={ch.type} onValueChange={v=>updA('charts',i,{type:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['line','bar','pie','area'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></div>)}
            </TabsContent>

            {/* 11. العدادات */}
            <TabsContent value="counters" className="mt-0 space-y-3">
              <SH icon={<Timer size={14} className="text-violet-600"/>} title="🔢 العدادات المتحركة" num="11/28" />
              <Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('counters',{counters:[...cms.counters,mkCounter()]})}><Plus size={10}/> إضافة</Button>
              {cms.counters.map((c,i)=><div key={c.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={c.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{c.visible?'ظاهر':'مخفي'}</Badge><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('counters',c.id)}><X size={10}/></Button></div><div className="grid grid-cols-2 gap-2"><Input value={c.title} onChange={e=>updA('counters',i,{title:e.target.value})} placeholder="العنوان" className="h-7 text-[10px]" /><Input type="number" value={c.value} onChange={e=>updA('counters',i,{value:Number(e.target.value)}as any)} placeholder="القيمة" className="h-7 text-[10px]" /><Input value={c.prefix} onChange={e=>updA('counters',i,{prefix:e.target.value})} placeholder="$" className="h-7 text-[10px]" /><Input value={c.suffix} onChange={e=>updA('counters',i,{suffix:e.target.value})} placeholder="ر.س" className="h-7 text-[10px]" /></div></div>)}
            </TabsContent>

            {/* 12-23. Quick sections */}
            <TabsContent value="achievements" className="mt-0 space-y-3"><SH icon={<Award size={14} className="text-violet-600"/>} title="🏆 الأوسمة" num="12/28" /><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('achievements',{achievements:[...cms.achievements,mkAch()]})}><Plus size={10}/> إضافة</Button>{cms.achievements.map((a,i)=><div key={a.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={a.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{a.visible?'ظاهر':'مخفي'}</Badge><div className="flex gap-1"><Button variant="ghost" size="sm" className="h-6" onClick={()=>updA('achievements',i,{visible:!a.visible})}><Eye size={10}/></Button><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('achievements',a.id)}><X size={10}/></Button></div></div><div className="grid grid-cols-2 gap-2"><Input value={a.name} onChange={e=>updA('achievements',i,{name:e.target.value})} placeholder="الاسم" className="h-7 text-[10px]" /><Input value={a.icon} onChange={e=>updA('achievements',i,{icon:e.target.value})} placeholder="🏆" className="h-7 text-[10px]" /><Select value={a.color} onValueChange={v=>updA('achievements',i,{color:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['gold','silver','bronze','custom'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Input value={a.description} onChange={e=>updA('achievements',i,{description:e.target.value})} placeholder="الوصف" className="h-7 text-[10px]" /></div></div>)}</TabsContent>

            <TabsContent value="banners" className="mt-0 space-y-3"><SH icon={<Sparkles size={14} className="text-violet-600"/>} title="📢 البانرات" num="13/28" /><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('banners',{banners:[...cms.banners,mkBanner()]})}><Plus size={10}/> إضافة</Button>{cms.banners.map((b,i)=><div key={b.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={b.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{b.visible?'ظاهر':'مخفي'}</Badge><div className="flex gap-1"><Button variant="ghost" size="sm" className="h-6" onClick={()=>updA('banners',i,{visible:!b.visible})}><Eye size={10}/></Button><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('banners',b.id)}><X size={10}/></Button></div></div><Input value={b.text} onChange={e=>updA('banners',i,{text:e.target.value})} placeholder="نص البانر" className="h-7 text-[10px]" /><div className="grid grid-cols-2 gap-2"><Select value={b.location} onValueChange={v=>updA('banners',i,{location:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['top','middle','bottom'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Toggle label="قابل للإغلاق" checked={b.closable} onChange={v=>updA('banners',i,{closable:v}as any)} /></div></div>)}</TabsContent>

            <TabsContent value="datatable" className="mt-0 space-y-3"><SH icon={<FileText size={14} className="text-violet-600"/>} title="📋 جدول البيانات" num="14/28" /><Toggle label="إظهار" checked={cms.dataTable.visible} onChange={v=>up('dataTable',{visible:v})} />{cms.dataTable.visible && <div className="space-y-2 border-t border-slate-100 pt-3"><Input value={cms.dataTable.title} onChange={e=>up('dataTable',{title:e.target.value})} placeholder="العنوان" className="h-8 text-xs" /><div className="grid grid-cols-2 gap-2"><Select value={cms.dataTable.sortOrder} onValueChange={v=>up('dataTable',{sortOrder:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="newest">الأحدث</SelectItem><SelectItem value="oldest">الأقدم</SelectItem></SelectContent></Select><Select value={String(cms.dataTable.maxRows)} onValueChange={v=>up('dataTable',{maxRows:Number(v) as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="5">5</SelectItem><SelectItem value="10">10</SelectItem><SelectItem value="20">20</SelectItem><SelectItem value="0">الكل</SelectItem></SelectContent></Select></div><Toggle label="بحث" checked={cms.dataTable.searchable} onChange={v=>up('dataTable',{searchable:v})} /><Select value={cms.dataTable.exportable} onValueChange={v=>up('dataTable',{exportable:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">بدون</SelectItem><SelectItem value="pdf">PDF</SelectItem><SelectItem value="excel">Excel</SelectItem></SelectContent></Select></div>}</TabsContent>

            <TabsContent value="map" className="mt-0 space-y-3"><SH icon={<MapPin size={14} className="text-violet-600"/>} title="🗺️ الخريطة" num="15/28" /><Toggle label="تفعيل" checked={cms.map.enabled} onChange={v=>up('map',{enabled:v})} />{cms.map.enabled && <div className="grid grid-cols-2 gap-2 border-t border-slate-100 pt-3"><Input value={cms.map.title} onChange={e=>up('map',{title:e.target.value})} placeholder="العنوان" className="h-8 text-xs" /><Input value={cms.map.lat} onChange={e=>up('map',{lat:e.target.value})} placeholder="خط العرض" className="h-8 text-xs" /><Input value={cms.map.lng} onChange={e=>up('map',{lng:e.target.value})} placeholder="خط الطول" className="h-8 text-xs" /><Select value={cms.map.mapType} onValueChange={v=>up('map',{mapType:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="roadmap">عادية</SelectItem><SelectItem value="satellite">أقمار</SelectItem></SelectContent></Select></div>}</TabsContent>

            <TabsContent value="messages" className="mt-0 space-y-3"><SH icon={<MessageSquare size={14} className="text-violet-600"/>} title="💬 الرسائل" num="16/28" /><Toggle label="تفعيل" checked={cms.messages.enabled} onChange={v=>up('messages',{enabled:v})} />{cms.messages.enabled && <div className="space-y-2 border-t border-slate-100 pt-3"><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('messages',{messages:[...cms.messages.messages,{id:uid(),text:'',date:new Date().toISOString().split('T')[0],read:false,priority:'normal',sender:'الإدارة',visible:true}]})}><Plus size={10}/> إضافة</Button>{cms.messages.messages.map((m,i)=><div key={m.id} className="p-2 rounded border border-slate-200 bg-slate-50/50 space-y-1"><div className="flex justify-between"><span className="text-[10px] text-slate-400">{m.date}</span><Button variant="ghost" size="sm" className="h-5 text-red-500" onClick={()=>up('messages',{messages:cms.messages.messages.filter(x=>x.id!==m.id)})}><X size={10}/></Button></div><Input value={m.text} onChange={e=>{const a=[...cms.messages.messages];a[i]={...a[i],text:e.target.value};up('messages',{messages:a})}} placeholder="نص الرسالة" className="h-7 text-[10px]" /><Input value={m.sender} onChange={e=>{const a=[...cms.messages.messages];a[i]={...a[i],sender:e.target.value};up('messages',{messages:a})}} placeholder="المرسل" className="h-7 text-[10px]" /></div>)}</div>}</TabsContent>

            <TabsContent value="calendar" className="mt-0 space-y-3"><SH icon={<Calendar size={14} className="text-violet-600"/>} title="📅 التقويم" num="17/28" /><Toggle label="تفعيل" checked={cms.calendar.enabled} onChange={v=>up('calendar',{enabled:v})} />{cms.calendar.enabled && <div className="space-y-2 border-t border-slate-100 pt-3"><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('calendar',{events:[...cms.calendar.events,{id:uid(),type:'profits',title:'',date:'',time:'',description:'',status:'upcoming',color:'#3b82f6',repeat:'once',visible:true}]})}><Plus size={10}/> إضافة موعد</Button>{cms.calendar.events.map((ev,i)=><div key={ev.id} className="p-2 rounded border border-slate-200 bg-slate-50/50 space-y-1"><div className="flex justify-between"><span className="text-[10px] text-slate-400">{ev.date}</span><Button variant="ghost" size="sm" className="h-5 text-red-500" onClick={()=>up('calendar',{events:cms.calendar.events.filter(x=>x.id!==ev.id)})}><X size={10}/></Button></div><Input value={ev.title} onChange={e=>{const a=[...cms.calendar.events];a[i]={...a[i],title:e.target.value};up('calendar',{events:a})}} placeholder="العنوان" className="h-7 text-[10px]" /><div className="grid grid-cols-2 gap-1"><Input type="date" value={ev.date} onChange={e=>{const a=[...cms.calendar.events];a[i]={...a[i],date:e.target.value};up('calendar',{events:a})}} className="h-7 text-[10px]" /><Input type="time" value={ev.time} onChange={e=>{const a=[...cms.calendar.events];a[i]={...a[i],time:e.target.value};up('calendar',{events:a})}} className="h-7 text-[10px]" /></div></div>)}</div>}</TabsContent>

            <TabsContent value="gallery" className="mt-0 space-y-3"><SH icon={<Image size={14} className="text-violet-600"/>} title="📸 معرض الصور" num="18/28" /><Toggle label="تفعيل" checked={cms.gallery.enabled} onChange={v=>up('gallery',{enabled:v})} />{cms.gallery.enabled && <div className="space-y-2 border-t border-slate-100 pt-3"><div className="grid grid-cols-3 gap-2"><Select value={cms.gallery.display} onValueChange={v=>up('gallery',{display:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent>{['grid','slider','masonry'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={cms.gallery.size} onValueChange={v=>up('gallery',{size:v as any})}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent>{['small','medium','large'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Toggle label="تكبير" checked={cms.gallery.zoomOnClick} onChange={v=>up('gallery',{zoomOnClick:v})} /></div><label className="h-8 px-3 rounded border border-slate-200 text-xs cursor-pointer flex items-center gap-1 hover:bg-slate-50 w-fit"><Upload size={11}/>رفع صور<input type="file" accept="image/*" multiple className="hidden" onChange={e=>{Array.from(e.target.files||[]).forEach(f=>{const r=new FileReader();r.onload=()=>up('gallery',{images:[...cms.gallery.images,{id:uid(),src:String(r.result||''),description:'',category:'other'}]});r.readAsDataURL(f)})}}/></label><p className="text-[10px] text-slate-500">{cms.gallery.images.length} صورة</p></div>}</TabsContent>

            <TabsContent value="alerts" className="mt-0 space-y-3"><SH icon={<AlertTriangle size={14} className="text-violet-600"/>} title="🔔 التنبيهات" num="19/28" /><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('alerts',{alerts:[...cms.alerts,mkAlert()]})}><Plus size={10}/> إضافة</Button>{cms.alerts.map((a,i)=><div key={a.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={a.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{a.visible?'ظاهر':'مخفي'}</Badge><div className="flex gap-1"><Button variant="ghost" size="sm" className="h-6" onClick={()=>updA('alerts',i,{visible:!a.visible})}><Eye size={10}/></Button><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('alerts',a.id)}><X size={10}/></Button></div></div><Input value={a.text} onChange={e=>updA('alerts',i,{text:e.target.value})} placeholder="نص التنبيه" className="h-7 text-[10px]" /><div className="grid grid-cols-2 gap-2"><Select value={a.type} onValueChange={v=>updA('alerts',i,{type:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['info','success','warning','danger'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={a.location} onValueChange={v=>updA('alerts',i,{location:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['top','middle','bottom'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></div>)}</TabsContent>

            <TabsContent value="docs" className="mt-0 space-y-3"><SH icon={<FileDown size={14} className="text-violet-600"/>} title="📄 المستندات" num="20/28" /><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('documents',{documents:[...cms.documents,mkDoc()]})}><Plus size={10}/> إضافة</Button>{cms.documents.map((d,i)=><div key={d.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={d.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{d.visible?'ظاهر':'مخفي'}</Badge><div className="flex gap-1"><Button variant="ghost" size="sm" className="h-6" onClick={()=>updA('documents',i,{visible:!d.visible})}><Eye size={10}/></Button><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('documents',d.id)}><X size={10}/></Button></div></div><Input value={d.name} onChange={e=>updA('documents',i,{name:e.target.value})} placeholder="اسم المستند" className="h-7 text-[10px]" /><label className="h-7 px-2 rounded border border-slate-200 text-[10px] cursor-pointer flex items-center gap-1 w-fit hover:bg-slate-50"><Upload size={10}/>رفع<input type="file" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>updA('documents',i,{fileData:String(r.result||''),fileType:f.type,size:(f.size/1024).toFixed(1)+' KB'}as any);r.readAsDataURL(f)}}}/></label><Toggle label="زر تحميل" checked={d.showDownload} onChange={v=>updA('documents',i,{showDownload:v}as any)} /></div>)}</TabsContent>

            <TabsContent value="progress" className="mt-0 space-y-3"><SH icon={<Target size={14} className="text-violet-600"/>} title="🎯 أشرطة التقدم" num="21/28" /><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('progressBars',{progressBars:[...cms.progressBars,mkProg()]})}><Plus size={10}/> إضافة</Button>{cms.progressBars.map((p,i)=><div key={p.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={p.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{p.visible?'ظاهر':'مخفي'}</Badge><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('progressBars',p.id)}><X size={10}/></Button></div><div className="grid grid-cols-2 gap-2"><Input value={p.title} onChange={e=>updA('progressBars',i,{title:e.target.value})} placeholder="العنوان" className="h-7 text-[10px]" /><Input type="number" value={p.current} onChange={e=>updA('progressBars',i,{current:Number(e.target.value)}as any)} placeholder="الحالي" className="h-7 text-[10px]" /><Input type="number" value={p.target} onChange={e=>updA('progressBars',i,{target:Number(e.target.value)}as any)} placeholder="الهدف" className="h-7 text-[10px]" /><input type="color" value={p.color} onChange={e=>updA('progressBars',i,{color:e.target.value}as any)} className="h-7 w-8 rounded cursor-pointer" /></div><div className="flex items-center gap-2"><span className="text-[10px] text-slate-500">{p.target>0?Math.round(p.current/p.target*100):0}%</span><div className="flex-1 h-2 bg-slate-200 rounded-full"><div className="h-full rounded-full" style={{width:`${Math.min(100,p.target>0?p.current/p.target*100:0)}%`,backgroundColor:p.color}}/></div></div></div>)}</TabsContent>

            <TabsContent value="countdown" className="mt-0 space-y-3"><SH icon={<Clock size={14} className="text-violet-600"/>} title="⏱️ العد التنازلي" num="22/28" /><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={()=>up('countdowns',{countdowns:[...cms.countdowns,mkCd()]})}><Plus size={10}/> إضافة</Button>{cms.countdowns.map((c,i)=><div key={c.id} className="p-2 rounded-lg border border-slate-200 bg-slate-50/50 space-y-2"><div className="flex justify-between"><Badge className={c.visible?'bg-emerald-50 text-emerald-700':'bg-slate-200'}>{c.visible?'ظاهر':'مخفي'}</Badge><Button variant="ghost" size="sm" className="h-6 text-red-500" onClick={()=>rmA('countdowns',c.id)}><X size={10}/></Button></div><div className="grid grid-cols-2 gap-2"><Input value={c.title} onChange={e=>updA('countdowns',i,{title:e.target.value})} placeholder="العنوان" className="h-7 text-[10px]" /><Input type="date" value={c.targetDate} onChange={e=>updA('countdowns',i,{targetDate:e.target.value}as any)} className="h-7 text-[10px]" /><Input type="time" value={c.targetTime} onChange={e=>updA('countdowns',i,{targetTime:e.target.value}as any)} className="h-7 text-[10px]" /><input type="color" value={c.color} onChange={e=>updA('countdowns',i,{color:e.target.value}as any)} className="h-7 w-8 rounded cursor-pointer" /></div></div>)}</TabsContent>

            <TabsContent value="invoice" className="mt-0 space-y-3"><SH icon={<Receipt size={14} className="text-violet-600"/>} title="🧾 الفاتورة" num="23/28" /><Toggle label="تفعيل" checked={cms.invoice.enabled} onChange={v=>up('invoice',{enabled:v})} />{cms.invoice.enabled && <div className="space-y-2 border-t border-slate-100 pt-3"><Input value={cms.invoice.currency} onChange={e=>up('invoice',{currency:e.target.value})} placeholder="العملة" className="h-8 text-xs" /><Textarea value={cms.invoice.notes} onChange={e=>up('invoice',{notes:e.target.value})} rows={2} placeholder="ملاحظات" className="text-xs" /><div className="flex items-center justify-between"><label className="text-[10px] font-bold text-slate-700">البنود</label><Button variant="outline" size="sm" className="h-6 text-[10px]" onClick={()=>up('invoice',{items:[...cms.invoice.items,{label:'',amount:0,type:'credit'}]})}><Plus size={10}/></Button></div>{cms.invoice.items.map((it,idx)=><div key={idx} className="flex gap-1 mb-1"><Input value={it.label} onChange={e=>{const a=[...cms.invoice.items];a[idx]={...a[idx],label:e.target.value};up('invoice',{items:a})}} placeholder="البند" className="h-7 text-[10px] flex-1" /><Input type="number" value={it.amount} onChange={e=>{const a=[...cms.invoice.items];a[idx]={...a[idx],amount:Number(e.target.value)};up('invoice',{items:a})}} placeholder="المبلغ" className="h-7 text-[10px] w-20" /><Select value={it.type} onValueChange={v=>{const a=[...cms.invoice.items];a[idx]={...a[idx],type:v as any};up('invoice',{items:a})}}><SelectTrigger className="h-7 text-[10px] w-14"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="credit">+</SelectItem><SelectItem value="debit">-</SelectItem></SelectContent></Select><Button variant="ghost" size="sm" className="h-7 text-red-500" onClick={()=>up('invoice',{items:cms.invoice.items.filter((_,j)=>j!==idx)})}><X size={10}/></Button></div>)}</div>}</TabsContent>

            {/* 24. القوالب */}
            <TabsContent value="templates" className="mt-0 space-y-3"><SH icon={<LayoutTemplate size={14} className="text-violet-600"/>} title="🎨 القوالب الجاهزة" num="24/28" /><p className="text-[10px] text-slate-500">اختر قالباً — يمكنك تعديله بعد التطبيق</p><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">{CMS_TEMPLATES.map(tpl=><div key={tpl.id} className={`rounded-xl border-2 p-2.5 cursor-pointer transition-all hover:shadow-md ${cms.templateId===tpl.id?'border-violet-500 bg-violet-50':'border-slate-200 hover:border-violet-300 bg-white'}`}><span className="text-xs font-black text-slate-800">{tpl.name}</span><p className="text-[10px] text-slate-500 mb-2">{tpl.description}</p><div className="flex gap-1 mb-2">{tpl.design?.colors&&<><div className="w-4 h-4 rounded-full border border-slate-200" style={{backgroundColor:tpl.design.colors.primary}}/><div className="w-4 h-4 rounded-full border border-slate-200" style={{backgroundColor:tpl.design.colors.bgMain}}/></>}</div><Button size="sm" className={`w-full h-7 text-[10px] ${cms.templateId===tpl.id?'bg-violet-600 hover:bg-violet-700':'bg-slate-100 hover:bg-slate-200 text-slate-700'}`} onClick={()=>applyTpl(tpl.id)}>{cms.templateId===tpl.id?'مُطبَّق ✓':'تطبيق'}</Button></div>)}</div></TabsContent>

            {/* 25-27. التصميم */}
            <TabsContent value="design" className="mt-0 space-y-3"><SH icon={<Palette size={14} className="text-violet-600"/>} title="🎨 التصميم (25-27)" num="25-27/28" />
              <div className="border-t border-slate-100 pt-2"><label className="text-[10px] font-black text-slate-700 mb-2 block">🔤 الخطوط (25)</label><div className="grid grid-cols-2 md:grid-cols-3 gap-2"><div><label className="text-[9px] text-slate-500">خط العناوين</label><Select value={cms.design.fonts.heading} onValueChange={v=>up('design',{fonts:{...cms.design.fonts,heading:v}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['Cairo','Tajawal','IBM Plex Arabic','Rubik','Almarai'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><label className="text-[9px] text-slate-500">خط المحتوى</label><Select value={cms.design.fonts.body} onValueChange={v=>up('design',{fonts:{...cms.design.fonts,body:v}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['Cairo','Tajawal','IBM Plex Arabic','Rubik','Almarai'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><label className="text-[9px] text-slate-500">الحجم</label><Select value={cms.design.fonts.baseSize} onValueChange={v=>up('design',{fonts:{...cms.design.fonts,baseSize:v as any}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['small','normal','large'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><label className="text-[9px] text-slate-500">السماكة</label><Select value={cms.design.fonts.weight} onValueChange={v=>up('design',{fonts:{...cms.design.fonts,weight:v as any}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['normal','medium','bold'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><label className="text-[9px] text-slate-500">الاتجاه</label><Select value={cms.design.fonts.direction} onValueChange={v=>up('design',{fonts:{...cms.design.fonts,direction:v as any}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="rtl">RTL</SelectItem><SelectItem value="ltr">LTR</SelectItem></SelectContent></Select></div></div></div>
              <div className="border-t border-slate-100 pt-2"><label className="text-[10px] font-black text-slate-700 mb-2 block">🖼️ الخلفيات (26)</label><div className="grid grid-cols-2 md:grid-cols-3 gap-2"><Select value={cms.design.background.type} onValueChange={v=>up('design',{background:{...cms.design.background,type:v as any}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['color','gradient','image','pattern'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><input type="color" value={cms.design.background.color} onChange={e=>up('design',{background:{...cms.design.background,color:e.target.value}})} className="h-7 w-full rounded cursor-pointer" /><Input type="number" min={0} max={100} value={cms.design.background.opacity} onChange={e=>up('design',{background:{...cms.design.background,opacity:Number(e.target.value)}})} placeholder="الشفافية %" className="h-7 text-[10px]" /><Input type="number" min={0} max={20} value={cms.design.background.blur} onChange={e=>up('design',{background:{...cms.design.background,blur:Number(e.target.value)}})} placeholder="الضبابية" className="h-7 text-[10px]" /><Toggle label="ثابتة" checked={cms.design.background.fixed} onChange={v=>up('design',{background:{...cms.design.background,fixed:v}})} /></div></div>
              <div className="border-t border-slate-100 pt-2"><label className="text-[10px] font-black text-slate-700 mb-2 block">📱 شاشة الاستعلام (27)</label><div className="grid grid-cols-2 md:grid-cols-3 gap-2"><Select value={cms.design.query.method} onValueChange={v=>up('design',{query:{...cms.design.query,method:v as any}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['phone','iban','code','name','multi'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={cms.design.query.inputStyle} onValueChange={v=>up('design',{query:{...cms.design.query,inputStyle:v as any}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['flat','raised','glass','rounded'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={cms.design.query.layout} onValueChange={v=>up('design',{query:{...cms.design.query,layout:v as any}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['dashboard','cards','list'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={String(cms.design.query.grid)} onValueChange={v=>up('design',{query:{...cms.design.query,grid:Number(v) as any}})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['1','2','3','4'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Input value={cms.design.query.welcomeTitle} onChange={e=>up('design',{query:{...cms.design.query,welcomeTitle:e.target.value}})} placeholder="عنوان الترحيب" className="h-7 text-[10px]" /><Input value={cms.design.query.loadingText} onChange={e=>up('design',{query:{...cms.design.query,loadingText:e.target.value}})} placeholder="رسالة التحميل" className="h-7 text-[10px]" /><Input value={cms.design.query.errorText} onChange={e=>up('design',{query:{...cms.design.query,errorText:e.target.value}})} placeholder="رسالة الخطأ" className="h-7 text-[10px]" /><div><label className="text-[9px] text-slate-500">لون الزر</label><input type="color" value={cms.design.query.buttonColor} onChange={e=>up('design',{query:{...cms.design.query,buttonColor:e.target.value}})} className="h-7 w-8 rounded cursor-pointer" /></div></div><Toggle label="تصفح بالسحب" checked={cms.design.query.swipeNav} onChange={v=>up('design',{query:{...cms.design.query,swipeNav:v}})} /></div>
              <div className="border-t border-slate-100 pt-2"><label className="text-[10px] font-black text-slate-700 mb-2 block">🎨 إعدادات الداشبورد</label><div className="grid grid-cols-2 md:grid-cols-3 gap-2"><Select value={cms.design.layout} onValueChange={v=>up('design',{layout:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['dashboard','cards','list'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={String(cms.design.grid)} onValueChange={v=>up('design',{grid:Number(v) as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['1','2','3','4'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={cms.design.cardStyle} onValueChange={v=>up('design',{cardStyle:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['flat','shadow','border','glass','neumorphism'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={cms.design.corners} onValueChange={v=>up('design',{corners:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['sharp','slight','very-rounded'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={cms.design.hoverEffect} onValueChange={v=>up('design',{hoverEffect:v as any})}><SelectTrigger className="h-7 text-[10px]"><SelectValue/></SelectTrigger><SelectContent>{['zoom','lift','glow','none'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></div>
            </TabsContent>

            {/* 28. إضافات */}
            <TabsContent value="widgets" className="mt-0 space-y-3"><SH icon={<Globe size={14} className="text-violet-600"/>} title="🧩 عناصر إضافية" num="28/28" /><div className="grid grid-cols-2 md:grid-cols-3 gap-2"><Toggle label="🕐 ساعة" checked={cms.widgets.liveClock} onChange={v=>up('widgets',{liveClock:v})} /><Toggle label="📅 هجري" checked={cms.widgets.hijriDate} onChange={v=>up('widgets',{hijriDate:v})} /><Toggle label="💱 عملات" checked={cms.widgets.currencyRates} onChange={v=>up('widgets',{currencyRates:v})} /><Toggle label="🥇 ذهب" checked={cms.widgets.goldPrice} onChange={v=>up('widgets',{goldPrice:v})} /><Toggle label="₿ بتكوين" checked={cms.widgets.btcPrice} onChange={v=>up('widgets',{btcPrice:v})} /><Toggle label="🌤️ طقس" checked={cms.widgets.weather} onChange={v=>up('widgets',{weather:v})} /><Toggle label="🧮 حاسبة" checked={cms.widgets.profitCalculator} onChange={v=>up('widgets',{profitCalculator:v})} /><Toggle label="📱 QR" checked={cms.widgets.qrCode} onChange={v=>up('widgets',{qrCode:v})} /><Toggle label="📰 شريط أخبار" checked={cms.widgets.newsTicker} onChange={v=>up('widgets',{newsTicker:v})} /></div>{cms.widgets.newsTicker && <Input value={cms.widgets.newsTickerText} onChange={e=>up('widgets',{newsTickerText:e.target.value})} placeholder="نص شريط الأخبار..." className="h-8 text-xs" />}</TabsContent>

          </div>
        </Tabs>
      </CardContent>
    </Card>
  );
}
